# Generated by Django 4.2.7 on 2023-12-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('animeid', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('generos', models.TextField()),
                ('formato', models.TextField()),
                ('episodios', models.IntegerField()),
            ],
            options={
                'ordering': ('titulo', 'animeid'),
            },
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.IntegerField()),
                ('animeid', models.IntegerField()),
                ('puntuacion', models.IntegerField()),
            ],
            options={
                'ordering': ('idUsuario', 'animeid'),
            },
        ),
    ]
