# Generated by Django 4.2.7 on 2023-12-20 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_puntuacion_animeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='anime',
            name='generos',
        ),
        migrations.AlterField(
            model_name='puntuacion',
            name='animeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones', to='principal.anime'),
        ),
        migrations.AddField(
            model_name='anime',
            name='generos',
            field=models.ManyToManyField(related_name='generos', to='principal.genero'),
        ),
    ]
